/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import java.util.Calendar;
import java.util.GregorianCalendar;

/**
 *
 * @author fatycalderon
 */
public class frmPrincipal extends javax.swing.JFrame implements Runnable {

    /**
     * Creates new form frmPrincipal
     */
   Calendar fecha=new GregorianCalendar();
    public frmPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        int anio = fecha.get(Calendar.YEAR);
        int mes = fecha.get(Calendar.MONTH);
        int dia = fecha.get(Calendar.DAY_OF_MONTH);
        int hora = fecha.get(Calendar.HOUR_OF_DAY);
        int minuto = fecha.get(Calendar.MINUTE);
        int segundo = fecha.get(Calendar.SECOND);
        
        txtFecha.setText(" Fecha Actual: "
                           + dia + "/" + (mes+1) + "/" + anio);
        txtHora.setText(" Hora Actual:"+hora+":"+minuto+":"+segundo);

    }
    
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        txtHora = new javax.swing.JTextField();
        lblIcono = new javax.swing.JLabel();
        MenuBarPRINCIPAL = new javax.swing.JMenuBar();
        MenuVer = new javax.swing.JMenu();
        menuVerLibro = new javax.swing.JMenuItem();
        menuVercatalogo = new javax.swing.JMenuItem();
        menucrear = new javax.swing.JMenu();
        crearAsiento = new javax.swing.JMenuItem();
        menuEstadosfinancieros = new javax.swing.JMenu();
        menuItemER = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        mnMayorizar = new javax.swing.JMenu();
        mayor = new javax.swing.JMenuItem();
        ajustes = new javax.swing.JMenu();
        realizarAjuste = new javax.swing.JMenuItem();
        cierre = new javax.swing.JMenu();
        RealizarCierre = new javax.swing.JMenuItem();
        salir = new javax.swing.JMenu();
        mnitemSalir = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem4.setText("jMenuItem4");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(54, 235, 4));
        jPanel1.setForeground(new java.awt.Color(21, 52, 197));

        jLabel1.setFont(new java.awt.Font("Nimbus Sans L", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(32, 33, 186));
        jLabel1.setText("Sistema Contable");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(193, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(177, 177, 177))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(0, 39, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, -1));

        jPanel2.setBackground(new java.awt.Color(91, 238, 14));

        jLabel2.setFont(new java.awt.Font("Carlito", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(21, 21, 205));
        jLabel2.setText("FATIMA DEL ROSARIO CALDERON LOPEZ    CL16006");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(451, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 527, 850, 90));

        txtFecha.setEditable(false);
        txtFecha.setBackground(new java.awt.Color(131, 129, 219));
        txtFecha.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        txtFecha.setForeground(new java.awt.Color(242, 1, 4));
        txtFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaActionPerformed(evt);
            }
        });
        getContentPane().add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, 260, -1));

        txtHora.setEditable(false);
        txtHora.setBackground(new java.awt.Color(112, 138, 222));
        txtHora.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        txtHora.setForeground(new java.awt.Color(244, 16, 10));
        getContentPane().add(txtHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 480, 240, -1));

        lblIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/conta1.png"))); // NOI18N
        getContentPane().add(lblIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 96, 850, 440));

        MenuVer.setBackground(new java.awt.Color(193, 12, 17));
        MenuVer.setText("VER");

        menuVerLibro.setText("Ver Libro Diario");
        menuVerLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVerLibroActionPerformed(evt);
            }
        });
        MenuVer.add(menuVerLibro);

        menuVercatalogo.setText("Ver Catalogo");
        menuVercatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVercatalogoActionPerformed(evt);
            }
        });
        MenuVer.add(menuVercatalogo);

        MenuBarPRINCIPAL.add(MenuVer);

        menucrear.setBackground(new java.awt.Color(50, 234, 236));
        menucrear.setText("CREAR");

        crearAsiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-venta-tienda-financiamiento-finanzas-pago-de-dinero-compras-10-48.png"))); // NOI18N
        crearAsiento.setText("Crear Asiento Contable");
        crearAsiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearAsientoActionPerformed(evt);
            }
        });
        menucrear.add(crearAsiento);

        MenuBarPRINCIPAL.add(menucrear);

        menuEstadosfinancieros.setBackground(new java.awt.Color(222, 48, 135));
        menuEstadosfinancieros.setText("ESTADOS FINANCIEROS");

        menuItemER.setText("Estado de Resultados");
        menuItemER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemERActionPerformed(evt);
            }
        });
        menuEstadosfinancieros.add(menuItemER);

        jMenuItem6.setText("Estado de Variacion de Capital");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        menuEstadosfinancieros.add(jMenuItem6);

        jMenuItem7.setText("Balance General");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        menuEstadosfinancieros.add(jMenuItem7);

        MenuBarPRINCIPAL.add(menuEstadosfinancieros);

        mnMayorizar.setText("MAYORIZACION");

        mayor.setText("mayorizar");
        mayor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mayorActionPerformed(evt);
            }
        });
        mnMayorizar.add(mayor);

        MenuBarPRINCIPAL.add(mnMayorizar);

        ajustes.setText("AJUSTES");

        realizarAjuste.setText("Realizar Ajuste");
        realizarAjuste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizarAjusteActionPerformed(evt);
            }
        });
        ajustes.add(realizarAjuste);

        MenuBarPRINCIPAL.add(ajustes);

        cierre.setText("CIERRE");

        RealizarCierre.setText("Realizar Cierre");
        RealizarCierre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RealizarCierreActionPerformed(evt);
            }
        });
        cierre.add(RealizarCierre);

        MenuBarPRINCIPAL.add(cierre);

        salir.setText("SALIR");

        mnitemSalir.setText("salir del programa");
        mnitemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitemSalirActionPerformed(evt);
            }
        });
        salir.add(mnitemSalir);

        MenuBarPRINCIPAL.add(salir);

        setJMenuBar(MenuBarPRINCIPAL);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuVerLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVerLibroActionPerformed
        // TODO add your handling code here:
           frmLibroDiarioVer p=new frmLibroDiarioVer();
        p.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuVerLibroActionPerformed

    private void menuVercatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVercatalogoActionPerformed
        // TODO add your handling code here:
         frmCatalogoContable catalogo=new frmCatalogoContable();
        catalogo.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuVercatalogoActionPerformed

    private void crearAsientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearAsientoActionPerformed
        // TODO add your handling code here:
        frmLibroDiario ld=new frmLibroDiario();
        ld.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_crearAsientoActionPerformed

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaActionPerformed

    private void mnitemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitemSalirActionPerformed
        // TODO add your handling code here:
         System.exit(0);
    }//GEN-LAST:event_mnitemSalirActionPerformed

    private void menuItemERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemERActionPerformed
        frmEstadoResultados cc=new frmEstadoResultados();
        cc.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuItemERActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        frmBalanceGeneral cc=new frmBalanceGeneral();
        cc.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        frmVariacionCapital cc=new frmVariacionCapital();
        cc.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void mayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mayorActionPerformed
        Mayorizacion m=new Mayorizacion();
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mayorActionPerformed

    private void realizarAjusteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realizarAjusteActionPerformed
        // TODO add your handling code here:
        Ajustes a=new Ajustes();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_realizarAjusteActionPerformed

    private void RealizarCierreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RealizarCierreActionPerformed
        // TODO add your handling code here:
        Cierre c=new Cierre();
        c.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_RealizarCierreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MenuBarPRINCIPAL;
    private javax.swing.JMenu MenuVer;
    private javax.swing.JMenuItem RealizarCierre;
    private javax.swing.JMenu ajustes;
    private javax.swing.JMenu cierre;
    private javax.swing.JMenuItem crearAsiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblIcono;
    private javax.swing.JMenuItem mayor;
    private javax.swing.JMenu menuEstadosfinancieros;
    private javax.swing.JMenuItem menuItemER;
    private javax.swing.JMenuItem menuVerLibro;
    private javax.swing.JMenuItem menuVercatalogo;
    private javax.swing.JMenu menucrear;
    private javax.swing.JMenu mnMayorizar;
    private javax.swing.JMenuItem mnitemSalir;
    private javax.swing.JMenuItem realizarAjuste;
    private javax.swing.JMenu salir;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtHora;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
